/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AlertCreateNestedManyWithoutPrepaidMetersInput } from "./AlertCreateNestedManyWithoutPrepaidMetersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { CommandCreateNestedManyWithoutPrepaidMetersInput } from "./CommandCreateNestedManyWithoutPrepaidMetersInput";
import { MeterDataCreateNestedManyWithoutPrepaidMetersInput } from "./MeterDataCreateNestedManyWithoutPrepaidMetersInput";
import { EnumPrepaidMeterStatus } from "./EnumPrepaidMeterStatus";

@InputType()
class PrepaidMeterCreateInput {
  @ApiProperty({
    required: false,
    type: () => AlertCreateNestedManyWithoutPrepaidMetersInput,
  })
  @ValidateNested()
  @Type(() => AlertCreateNestedManyWithoutPrepaidMetersInput)
  @IsOptional()
  @Field(() => AlertCreateNestedManyWithoutPrepaidMetersInput, {
    nullable: true,
  })
  alerts?: AlertCreateNestedManyWithoutPrepaidMetersInput;

  @ApiProperty({
    required: false,
    type: () => CommandCreateNestedManyWithoutPrepaidMetersInput,
  })
  @ValidateNested()
  @Type(() => CommandCreateNestedManyWithoutPrepaidMetersInput)
  @IsOptional()
  @Field(() => CommandCreateNestedManyWithoutPrepaidMetersInput, {
    nullable: true,
  })
  commands?: CommandCreateNestedManyWithoutPrepaidMetersInput;

  @ApiProperty({
    required: false,
    type: () => MeterDataCreateNestedManyWithoutPrepaidMetersInput,
  })
  @ValidateNested()
  @Type(() => MeterDataCreateNestedManyWithoutPrepaidMetersInput)
  @IsOptional()
  @Field(() => MeterDataCreateNestedManyWithoutPrepaidMetersInput, {
    nullable: true,
  })
  meterDataItems?: MeterDataCreateNestedManyWithoutPrepaidMetersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  meterNumber?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumPrepaidMeterStatus,
  })
  @IsEnum(EnumPrepaidMeterStatus)
  @IsOptional()
  @Field(() => EnumPrepaidMeterStatus, {
    nullable: true,
  })
  status?: "Option1" | null;
}

export { PrepaidMeterCreateInput as PrepaidMeterCreateInput };
