/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Meter } from "./Meter";
import { MeterCountArgs } from "./MeterCountArgs";
import { MeterFindManyArgs } from "./MeterFindManyArgs";
import { MeterFindUniqueArgs } from "./MeterFindUniqueArgs";
import { CreateMeterArgs } from "./CreateMeterArgs";
import { UpdateMeterArgs } from "./UpdateMeterArgs";
import { DeleteMeterArgs } from "./DeleteMeterArgs";
import { UsageFindManyArgs } from "../../usage/base/UsageFindManyArgs";
import { Usage } from "../../usage/base/Usage";
import { User } from "../../user/base/User";
import { MeterService } from "../meter.service";
@graphql.Resolver(() => Meter)
export class MeterResolverBase {
  constructor(protected readonly service: MeterService) {}

  async _metersMeta(
    @graphql.Args() args: MeterCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Meter])
  async meters(@graphql.Args() args: MeterFindManyArgs): Promise<Meter[]> {
    return this.service.meters(args);
  }

  @graphql.Query(() => Meter, { nullable: true })
  async meter(
    @graphql.Args() args: MeterFindUniqueArgs
  ): Promise<Meter | null> {
    const result = await this.service.meter(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Meter)
  async createMeter(@graphql.Args() args: CreateMeterArgs): Promise<Meter> {
    return await this.service.createMeter({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Meter)
  async updateMeter(
    @graphql.Args() args: UpdateMeterArgs
  ): Promise<Meter | null> {
    try {
      return await this.service.updateMeter({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Meter)
  async deleteMeter(
    @graphql.Args() args: DeleteMeterArgs
  ): Promise<Meter | null> {
    try {
      return await this.service.deleteMeter(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Usage], { name: "usages" })
  async findUsages(
    @graphql.Parent() parent: Meter,
    @graphql.Args() args: UsageFindManyArgs
  ): Promise<Usage[]> {
    const results = await this.service.findUsages(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Meter): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
