/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsJSONValue } from "../../validators";
import {
  IsOptional,
  IsDate,
  IsEnum,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { Type } from "class-transformer";
import { EnumMeterStatus } from "./EnumMeterStatus";
import { UsageCreateNestedManyWithoutMetersInput } from "./UsageCreateNestedManyWithoutMetersInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class MeterCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  coordinates?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  installationDate?: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumMeterStatus,
  })
  @IsEnum(EnumMeterStatus)
  @IsOptional()
  @Field(() => EnumMeterStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  tokenBalance?: number | null;

  @ApiProperty({
    required: false,
    type: () => UsageCreateNestedManyWithoutMetersInput,
  })
  @ValidateNested()
  @Type(() => UsageCreateNestedManyWithoutMetersInput)
  @IsOptional()
  @Field(() => UsageCreateNestedManyWithoutMetersInput, {
    nullable: true,
  })
  usages?: UsageCreateNestedManyWithoutMetersInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { MeterCreateInput as MeterCreateInput };
