/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MeterService } from "../meter.service";
import { MeterCreateInput } from "./MeterCreateInput";
import { Meter } from "./Meter";
import { MeterFindManyArgs } from "./MeterFindManyArgs";
import { MeterWhereUniqueInput } from "./MeterWhereUniqueInput";
import { MeterUpdateInput } from "./MeterUpdateInput";
import { UsageFindManyArgs } from "../../usage/base/UsageFindManyArgs";
import { Usage } from "../../usage/base/Usage";
import { UsageWhereUniqueInput } from "../../usage/base/UsageWhereUniqueInput";

export class MeterControllerBase {
  constructor(protected readonly service: MeterService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Meter })
  async createMeter(@common.Body() data: MeterCreateInput): Promise<Meter> {
    return await this.service.createMeter({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        coordinates: true,
        createdAt: true,
        id: true,
        installationDate: true,
        status: true,
        tokenBalance: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Meter] })
  @ApiNestedQuery(MeterFindManyArgs)
  async meters(@common.Req() request: Request): Promise<Meter[]> {
    const args = plainToClass(MeterFindManyArgs, request.query);
    return this.service.meters({
      ...args,
      select: {
        coordinates: true,
        createdAt: true,
        id: true,
        installationDate: true,
        status: true,
        tokenBalance: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Meter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async meter(
    @common.Param() params: MeterWhereUniqueInput
  ): Promise<Meter | null> {
    const result = await this.service.meter({
      where: params,
      select: {
        coordinates: true,
        createdAt: true,
        id: true,
        installationDate: true,
        status: true,
        tokenBalance: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Meter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMeter(
    @common.Param() params: MeterWhereUniqueInput,
    @common.Body() data: MeterUpdateInput
  ): Promise<Meter | null> {
    try {
      return await this.service.updateMeter({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          coordinates: true,
          createdAt: true,
          id: true,
          installationDate: true,
          status: true,
          tokenBalance: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Meter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMeter(
    @common.Param() params: MeterWhereUniqueInput
  ): Promise<Meter | null> {
    try {
      return await this.service.deleteMeter({
        where: params,
        select: {
          coordinates: true,
          createdAt: true,
          id: true,
          installationDate: true,
          status: true,
          tokenBalance: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/usages")
  @ApiNestedQuery(UsageFindManyArgs)
  async findUsages(
    @common.Req() request: Request,
    @common.Param() params: MeterWhereUniqueInput
  ): Promise<Usage[]> {
    const query = plainToClass(UsageFindManyArgs, request.query);
    const results = await this.service.findUsages(params.id, {
      ...query,
      select: {
        amountUsed: true,
        createdAt: true,
        id: true,

        meter: {
          select: {
            id: true,
          },
        },

        meterRelation: true,
        updatedAt: true,
        usageDate: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/usages")
  async connectUsages(
    @common.Param() params: MeterWhereUniqueInput,
    @common.Body() body: UsageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      usages: {
        connect: body,
      },
    };
    await this.service.updateMeter({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/usages")
  async updateUsages(
    @common.Param() params: MeterWhereUniqueInput,
    @common.Body() body: UsageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      usages: {
        set: body,
      },
    };
    await this.service.updateMeter({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/usages")
  async disconnectUsages(
    @common.Param() params: MeterWhereUniqueInput,
    @common.Body() body: UsageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      usages: {
        disconnect: body,
      },
    };
    await this.service.updateMeter({
      where: params,
      data,
      select: { id: true },
    });
  }
}
